### ISSUE TITLE
java.lang.IllegalArgumentException: null when serialize object with byte arrays

### ISSUE THREAD

**Issue by p0st1t** [near/borshj#4]
Hello, first of all thank you very much for your work.

I have a problem with the serialization of an object including:

- 2 byte arrays (size 32)
- 2 bytes

here is my class:

```
public class PlayerAccount implements Borsh {

    public byte[] owner = new byte[32];
    public byte[] nft_addr = new byte[32];
    public byte is_waiting_match_making;
    public byte is_waiting_battle_royal;

    public PlayerAccount() {}

    public PlayerAccount(byte[] owner, byte[] nft_addr, byte is_waiting_match_making, byte is_waiting_battle_royal) {
        this.owner = owner;
        this.nft_addr = nft_addr;
        this.is_waiting_battle_royal = is_waiting_battle_royal;
        this.is_waiting_match_making = is_waiting_match_making;
    }

}
```

And this is where i try to serialize it : 

```
    private static final PublicKey PROGRAM_ID = new PublicKey("E8UdsnAhN6EFZueXbmt8aNGqA6RJb1uAwwBpv2ySecox");

    public void fetchPlayers()  {
        PlayerAccount playerAccount = new PlayerAccount();
        playerAccount.is_waiting_battle_royal = 1;
        playerAccount.is_waiting_match_making = 1;
        playerAccount.nft_addr = PROGRAM_ID.toByteArray();
        playerAccount.owner = PROGRAM_ID.toByteArray();
        Borsh.serialize(playerAccount);
    }
```

But it fail, this is the stacktrace : 

```
java.lang.IllegalArgumentException: null
        at org.near.borshj.BorshOutput.write(BorshOutput.java:53) ~[borshj-0.0.0.jar!/:na]
        at org.near.borshj.BorshOutput.writePOJO(BorshOutput.java:60) ~[borshj-0.0.0.jar!/:na]
        at org.near.borshj.BorshOutput.write(BorshOutput.java:51) ~[borshj-0.0.0.jar!/:na]
        at org.near.borshj.Borsh.serialize(Borsh.java:17) ~[borshj-0.0.0.jar!/:na]
        at com.squidwar.warzone.service.PlayerFetch.fetchPlayers(PlayerFetch.java:39) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.13.jar!/:5.3.13]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.13.jar!/:5.3.13]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

Without the two arrays it serialize successfully,  so i think i'm missing something with the gestion of byte arrays with borshj...

So, i'm sorry to open an issue for that, maybe it's stupid, but do you know how can i fix it please?

i hope surely not bother you with stupid question, thanks in advance for any help..

**Comment by p0st1t** [comment]
Ok, i just saw this part of code : 

```
  default public @NonNull Self write(final @NonNull Object object) {
    requireNonNull(object);
    if (object instanceof Byte) {
      return this.writeU8((byte)object);
    }
    else if (object instanceof Short) {
      return this.writeU16((short)object);
    }
    else if (object instanceof Integer) {
      return this.writeU32((int)object);
    }
    else if (object instanceof Long) {
      return this.writeU64((long)object);
    }
    else if (object instanceof Float) {
      return this.writeF32((float)object);
    }
    else if (object instanceof Double) {
      return this.writeF64((double)object);
    }
    else if (object instanceof BigInteger) {
      return this.writeU128((BigInteger)object);
    }
    else if (object instanceof String) {
      return this.writeString((String)object);
    }
    else if (object instanceof List) {
      return (Self)this.writeArray((List)object);
    }
    else if (object instanceof Boolean) {
      return (Self)this.writeBoolean((Boolean)object);
    }
    else if (object instanceof Optional) {
      return (Self)this.writeOptional((Optional)object);
    }
    else if (object instanceof Borsh) {
      return this.writePOJO(object);
    }
    throw new IllegalArgumentException();
  }
```

So i understand the primitive byte[] isn't possible here. 

I try with a List, and close the issue if it works :)

**Comment by p0st1t** [comment]
As i understand when i read the BorshOutput class, at this part : 

```
  default public <T> T read(final @NonNull Class klass) {
    if (klass == Byte.class || klass == byte.class) {
      return (T)Byte.valueOf(this.readU8());
    }
    else if (klass == Short.class || klass == short.class) {
      return (T)Short.valueOf(this.readU16());
    }
    else if (klass == Integer.class || klass == int.class) {
      return (T)Integer.valueOf(this.readU32());
    }
    else if (klass == Long.class || klass == long.class) {
      return (T)Long.valueOf(this.readU64());
    }
    else if (klass == BigInteger.class) {
      return (T)this.readU128();
    }
    else if (klass == Float.class || klass == float.class) {
      return (T)Float.valueOf(this.readF32());
    }
    else if (klass == Double.class || klass == double.class) {
      return (T)Double.valueOf(this.readF64());
    }
    else if (klass == String.class) {
      return (T)this.readString();
    }
    else if (klass == Boolean.class) {
      return (T)Boolean.valueOf(this.readBoolean());
    }
    else if (klass == Optional.class) {
      return (T)this.readOptional();
    }
    else if (Borsh.isSerializable(klass)) {
      return (T)this.readPOJO(klass);
    }
    throw new IllegalArgumentException();
  }
```

primitive byte array isn't in theses conditions, so as i understand i need to use a List of Byte

The serialization seems to work with List<Byte>. But the deserialization don't work :(

In the BorshInput class there is no List  type  in conditions...

```
  default public <T> T read(final @NonNull Class klass) {
    if (klass == Byte.class || klass == byte.class) {
      return (T)Byte.valueOf(this.readU8());
    }
    else if (klass == Short.class || klass == short.class) {
      return (T)Short.valueOf(this.readU16());
    }
    else if (klass == Integer.class || klass == int.class) {
      return (T)Integer.valueOf(this.readU32());
    }
    else if (klass == Long.class || klass == long.class) {
      return (T)Long.valueOf(this.readU64());
    }
    else if (klass == BigInteger.class) {
      return (T)this.readU128();
    }
    else if (klass == Float.class || klass == float.class) {
      return (T)Float.valueOf(this.readF32());
    }
    else if (klass == Double.class || klass == double.class) {
      return (T)Double.valueOf(this.readF64());
    }
    else if (klass == String.class) {
      return (T)this.readString();
    }
    else if (klass == Boolean.class) {
      return (T)Boolean.valueOf(this.readBoolean());
    }
    else if (klass == Optional.class) {
      return (T)this.readOptional();
    }
    else if (Borsh.isSerializable(klass)) {
      return (T)this.readPOJO(klass);
    }
    throw new IllegalArgumentException();
  }
```

What i am missing please? It begin to make me crazy ><
